Fix "rugged" gem install
When running bin/setup to install the gems I hit this error:

```
Installing rugged 1.5.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/david.read/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rugged-1.5.1/ext/rugged
/Users/david.read/.rbenv/versions/3.2.1/bin/ruby -I /Users/david.read/.rbenv/versions/3.2.1/lib/ruby/3.2.0 extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
```

I fixed it by installing cmake, so I've added it to the README.

Also brew's postgres needs to be started manually on every boot by default, so for convenience I added the command to get it to launch on every boot.